[global]
log_level = 'trace'

[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[rest]
enabled = false
host = '0.0.0.0'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001


[[chains]]
id = 'provider-chain'
rpc_addr = 'http://192.168.33.11:26657'
grpc_addr = 'http://192.168.33.11:9090'
event_source = { mode = 'push', url = 'ws://192.168.33.11:26657/websocket', batch_delay = '200ms' }
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'default'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 1800000
max_gas = 9000000
gas_price = { price = 0.025, denom = 'icsstake' }
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 179999
clock_drift = '15s'
max_block_time = '10s'
trusting_period = '80m'
trust_threshold = { numerator = '2', denominator = '3' }


[[chains]]
id = 'consumer-chain'
rpc_addr = 'http://192.168.33.21:26657'
grpc_addr = 'http://192.168.33.21:9090'
event_source = { mode = 'push', url = 'ws://192.168.33.21:26657/websocket', batch_delay = '200ms' }
rpc_timeout = '10s'
account_prefix = 'consumer'
key_name = 'default'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 1800000
max_gas = 9000000
gas_price = { price = 0.025, denom = 'ustake' }
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 179999
clock_drift = '15s'
max_block_time = '10s'
trusting_period = '80m'
trust_threshold = { numerator = '2', denominator = '3' }
ccv_consumer_chain = true